export const APP = {
    TOGGLEMENU: 'app/TOGGLEMENU',
    TOGGLESUBMENU: 'app/TOGGLESUBMENU',
    USER: 'app/USER',
    IMG: 'app/IMG'
}
export const MENU = {
    MENU: 'MENU/MENU',
    CADASTRO: 'MENU/CADASTRO',
    PEDIDO: 'MENU/PEDIDO',
    CONFIGURACAO: 'MENU/CONFIGURACAO',
}