export const APP = {
    TOGGLEMENU: 'app/TOGGLEMENU',
    TOGGLESUBMENU: 'app/TOGGLESUBMENU',
    USER: 'app/USER',
    IMG: 'app/IMG',
    MENU: 'app/MENU',
    CADASTRO: 'app/CADASTRO',
    PEDIDO: 'app/PEDIDO',
    CONFIGURACAO: 'app/CONFIGURACAO',
    NOTSUBMENU: 'app/NOTSUBMENU'
}

export const PAGE = {
    STATE: 'page/STATE',
    NAMEPATH: 'page/NAMEPATH',
    PAGELOAD: 'page/LOAD',
    BEFORESAVE: 'page/BEFORESAVE',
    BEFOREEDIT: 'page/BEFOREEDIT',
    BEFORECANCEL: 'page/BEFORECANCEL',
    BEFOREBACK: 'page/BEFOREBACK',
    BEFORENEW: 'page/BEFORENEW',
}
